name: Python CI

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v3  # Using v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4  # Using v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Debug Step: Confirm Python and pip are installed
      - name: Verify Python and pip installation
        run: |
          python --version
          pip --version
          pytest --version  # Check if pytest is installed

      # Step 4: Run tests
      - name: Run tests
        run: pytest
